/**
 * AI Mock 응답 — USE_AI_MOCK=true 시 Anthropic API 호출 없이 반환
 */

export const mockRfpParse = {
  projectInfo: {
    name: "차세대 통합정보시스템 구축",
    client: "한국전자통신연구원",
    budget_amount: 2500000000,
    bid_deadline: "2026-07-15",
    project_type: "si",
    category: "public",
    contract_method: "협상에 의한 계약",
    project_period: "계약일로부터 12개월",
    warranty_period: "검수 후 12개월",
  },
  rules: [
    {
      rule_type: "qualification",
      rule_target: "SW사업 실적",
      condition_type: "min",
      condition_value: { min_amount: 1000000000, min_count: 2 },
      source_type: "ai_extracted",
      source_text: "최근 3년간 유사 사업 수행실적 10억원 이상 2건",
      source_page: "12",
      needs_review: false,
      confidence: 0.92,
    },
    {
      rule_type: "subcontract",
      rule_target: "하도급 비율 제한",
      condition_type: "max",
      condition_value: { max_rate: 50 },
      source_type: "ai_extracted",
      source_text: "하도급 비율은 총 사업비의 50%를 초과할 수 없음",
      source_page: "18",
      needs_review: false,
      confidence: 0.95,
    },
    {
      rule_type: "proposal_format",
      rule_target: "제안서 형식",
      condition_type: "required",
      condition_value: { max_pages: 200, font_size: 11, line_spacing: 160 },
      source_type: "ai_extracted",
      source_text: "제안서는 A4 200매 이내, 11pt, 줄간격 160%",
      source_page: "8",
      needs_review: false,
      confidence: 0.88,
    },
    {
      rule_type: "eval_criteria",
      rule_target: "기술평가 배점",
      condition_type: "required",
      condition_value: { qualitative: 600, quantitative: 200, total: 800 },
      source_type: "ai_extracted",
      source_text: "기술능력평가 800점(정성 600점, 정량 200점)",
      source_page: "22",
      needs_review: false,
      confidence: 0.90,
    },
    {
      rule_type: "bid_deposit",
      rule_target: "입찰보증금",
      condition_type: "required",
      condition_value: { rate: 5, method: "보증보험증권" },
      source_type: "default",
      source_text: null,
      source_page: null,
      needs_review: true,
      confidence: 0.5,
    },
  ],
  documents: [
    {
      form_number: "서식-1",
      doc_name: "입찰참가신청서",
      submit_timing: "bid_time",
      rfp_page: "45",
      condition_note: "주) 법인인감 날인 필수",
      proof_items: [
        {
          item_name: "사업자등록증 사본",
          condition_type: "AND",
          condition_group: 1,
          min_required: 1,
          issuing_org: "국세청",
          validity_days: null,
          needs_review: false,
        },
        {
          item_name: "법인등기부등본",
          condition_type: "AND",
          condition_group: 1,
          min_required: 1,
          issuing_org: "대법원",
          validity_days: 90,
          needs_review: false,
        },
      ],
    },
    {
      form_number: "서식-3",
      doc_name: "SW사업 수행실적 확인서",
      submit_timing: "bid_time",
      rfp_page: "46",
      condition_note: "주) 아래 증빙 중 하나 이상 첨부",
      proof_items: [
        {
          item_name: "계약서 사본",
          condition_type: "OR",
          condition_group: 1,
          min_required: 1,
          issuing_org: null,
          validity_days: null,
          needs_review: false,
        },
        {
          item_name: "실적증명서",
          condition_type: "OR",
          condition_group: 1,
          min_required: 1,
          issuing_org: "발주기관",
          validity_days: null,
          needs_review: false,
        },
      ],
    },
    {
      form_number: "서식-5",
      doc_name: "신용평가등급 확인서",
      submit_timing: "bid_time",
      rfp_page: "47",
      condition_note: null,
      proof_items: [
        {
          item_name: "신용평가등급확인서",
          condition_type: "AND",
          condition_group: 1,
          min_required: 1,
          issuing_org: null,
          validity_days: 30,
          needs_review: true,
        },
      ],
    },
  ],
  laws: [
    {
      law_name: "소프트웨어 진흥법",
      article: "제24조(소프트웨어사업의 하도급)",
      content: "소프트웨어사업자는 도급받은 소프트웨어사업의 일부를 대통령령으로 정하는 비율과 범위를 초과하여 하도급할 수 없다.",
      url: null,
      is_current: true,
      needs_review: false,
    },
    {
      law_name: "국가를 당사자로 하는 계약에 관한 법률 시행령",
      article: "제42조(협상에 의한 계약체결)",
      content: "협상에 의한 계약을 체결하려는 경우 기술능력평가 점수가 배점한도의 85% 이상인 자를 협상적격자로 선정한다.",
      url: null,
      is_current: true,
      needs_review: false,
    },
  ],
};

export const mockDocumentValidate = {
  valid: {
    validation_status: "valid",
    validation_message: "서류가 유효합니다. 발급일 기준 유효기간 내입니다.",
    calculated_score: null,
    ai_issue_date: "2026-05-01",
    ai_expiry_date: "2026-08-01",
  },
  expiring_soon: {
    validation_status: "expiring_soon",
    validation_message: "서류는 유효하지만 만료일이 15일 이내입니다. 갱신을 권장합니다.",
    calculated_score: null,
    ai_issue_date: "2026-03-01",
    ai_expiry_date: "2026-06-15",
  },
  needs_review: {
    validation_status: "needs_review",
    validation_message: "발급일 또는 유효기간을 자동으로 판단할 수 없습니다. 담당자 확인이 필요합니다.",
    calculated_score: 8.5,
    ai_issue_date: null,
    ai_expiry_date: null,
  },
};

export const mockProposalEvaluate = {
  page_count: 187,
  format_valid: true,
  format_issues: [],
  has_reference_table: true,
  has_glossary: true,
  vague_expr_count: 3,
  qualitative_score: 75.0,
  quantitative_score: 85.0,
  tech_score_total: 80.0,
  threshold_pct: 85,
  threshold_score: 680,
  meets_threshold: true,
  coverage_rate: 92.5,
  weak_items: [
    { item: "보안 아키텍처", reason: "구체적인 암호화 방식 미명시" },
    { item: "데이터 마이그레이션", reason: "기존 시스템 데이터 검증 절차 미흡" },
  ],
  recommendations: [
    { type: "보완", message: "보안 아키텍처 섹션에 구체적인 암호화 알고리즘 및 키 관리 방안 추가 권장" },
    { type: "개선", message: "마이그레이션 섹션에 데이터 정합성 검증 단계 및 롤백 방안 명시 권장" },
    { type: "형식", message: "모호표현 3건 수정 권장: '검토 예정', '추후 결정', '~할 수 있음'" },
  ],
};
